### ISSUE TITLE
Check Docker 

### ISSUE THREAD

**Issue by tuefekci** [tuefekci/blkholePHP#5]
Hi,

Hope I don't bother you.

Are you still working on blkhole?

I tried compiling the docker image but I get this error about the
composer repository:

 > web@0.1.0 build
 > react-scripts build

Creating an optimized production build...
Compiled with warnings.

src/App.js
   Line 2:8:    'ReactDOM' is defined but never used no-unused-vars
   Line 11:44:  'NavDropdown' is defined but never used no-unused-vars
   Line 11:90:  'Alert' is defined but never used no-unused-vars
   Line 14:8:   'empty' is defined but never used no-unused-vars
   Line 24:3:   Useless constructor no-useless-constructor
   Line 30:17:  Expected '===' and instead saw '==' eqeqeq
   Line 61:55:  Expected '===' and instead saw '==' eqeqeq
   Line 206:3:  Useless constructor no-useless-constructor
   Line 213:9:  'stateData' is assigned a value but never used
no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

   110.6 KB  build/static/js/2.c995b646.chunk.js
   22.8 KB   build/static/css/2.c4e73993.chunk.css
   2.17 KB   build/static/js/main.7b4c70e9.chunk.js
   1.62 KB   build/static/js/3.c58c2153.chunk.js
   1.16 KB   build/static/js/runtime-main.7e1c94cd.js
   616 B     build/static/css/main.ffe19602.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

   npm install -g serve
   serve -s build

Find out more about deployment here:

   https://cra.link/deployment

Loading composer repositories with package information

In PathRepository.php line 154:

   The `url` supplied for the path (./../helpers) repository does not exist

update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run]
[--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader]
[--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies]
[-W|--with-all-dependencies] [-v|vv|vvv|--verbose]
[-o|--optimize-autoloader] [-a|--classmap-authoritative]
[--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX]
[--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs]
[--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs]
[--] [<packages>...]

Sending build context to Docker daemon  341.1MB
Step 1/6 : FROM php:7.4-cli
  ---> 345b2751a654
Step 2/6 : COPY . /srv/blkhole
  ---> Using cache
  ---> a7bb16844d81
Step 3/6 : WORKDIR /srv/blkhole
  ---> Using cache
  ---> 25ff2357c1c0
Step 4/6 : CMD [ "env >> /srv/blkhole/.env"]
  ---> Using cache
  ---> de1d3ded414d
Step 5/6 : CMD [ "php", "./main.php" ]
  ---> Using cache
  ---> 1e21fb2edb71
Step 6/6 : EXPOSE 1337
  ---> Using cache
  ---> cf4e0764e57e
Successfully built cf4e0764e57e
Successfully tagged blkhole:latest

Then when I try to run with the container:

Warning: require_once(/srv/blkhole/vendor/autoload.php): failed to open
stream: No such file or directory in /srv/blkhole/main.php on line 9

Fatal error: require_once(): Failed opening required
'/srv/blkhole/vendor/autoload.php' (include_path='.:/usr/local/lib/php')
in /srv/blkhole/main.php on line 9

I'd appreciate if you can help!

Thanks

Cheers

**Comment by tuefekci** [comment]
First, I don't know why you rebuild the frontend, there is a working build included in the build folder.

Second remove 
`   
 "repositories": [{
        "type": "path",
        "url": "./../helpers",
        "options": {
            "symlink": false
        }
    }],
`

From the composer json this is a shortcut for testing with the local build of my helpers library the other option is to just git clone tuefekci/helpers in the parent folder of the blkhole repo.

blkhole is not really battle tested because there is not a lot of response to it so if you find anything else wrong just open a ticket instead of emailing me.

**Comment by GreysonMannix** [comment]
> First, I don't know why you rebuild the frontend, there is a working build included in the build folder.

I'm not sure, just running the buildDocker.sh script :)
Guess since something is missing it's rebuilding it from scratch instead of using the included one.
You should try the script on a clean VM and see what happens.

> Second remove
That I figured out.
I had to remove also a lock file.
But despite not having errors in the build, it doesn't work properly after.
Clicking Settings doesn't work etc.

Thanks for the tip about the helpers!
I'll try and let you know.


> blkhole is not really battle tested because there is not a lot of response to it so if you find anything else wrong just open a ticket instead of emailing me.

It's a pity because is awesome!

**Comment by GreysonMannix** [comment]
This is the output with a clean download and the helpers from Github in the ./helpers directory

`

> web@0.1.0 build
> react-scripts build

sh: 1: react-scripts: Permission denied
npm ERR! code 127
npm ERR! path /srv/dev/blkhole/web
npm ERR! command failed
npm ERR! command sh -c react-scripts build

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/dev/home/dockerperson/.npm/_logs/2022-08-29T03_49_00_033Z-debug.log
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires tuefekci/helpers dev-main, it is satisfiable by tuefekci/helpers[dev-main] from composer repo (https://repo.packagist.org) but tuefekci/helpers[dev-master] from path repo (./helpers) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.

Sending build context to Docker daemon  10.67MB
Step 1/6 : FROM php:7.4-cli
 ---> 4e0e0b7c2ea8
Step 2/6 : COPY . /srv/blkhole
 ---> Using cache
 ---> fefebecb02e4
Step 3/6 : WORKDIR /srv/blkhole
 ---> Using cache
 ---> 9f8c5a050670
Step 4/6 : CMD [ "env >> /srv/blkhole/.env"]
 ---> Using cache
 ---> b4aafee5e2b3
Step 5/6 : CMD [ "php", "./main.php" ]
 ---> Using cache
 ---> 1062f2201769
Step 6/6 : EXPOSE 1337
 ---> Using cache
 ---> 1e6bc4fd76b1
Successfully built 1e6bc4fd76b1
Successfully tagged blkhole:latest

`

Tried with

npm install react-scripts --save

in the blkhole directory but

`
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'react-dom' in '/srv/dev/blkhole/web/src'

`

Did the same for react-dom, react-icons, bootstrap, locutus, web-vitals, react-bootstrap, axios

At the end is able to build the image but still doesn't work properly (Enter torrent button and settings unresponsive, doesn't pickup from blackhole directory).

Copy & paste a magnet link works but this time with the download helpers directory doesn't ever finish a download. Stuck at 100% and 0 bytes/s, after 3 the new one will hang with "waiting for a download slot".

**Comment by tuefekci** [comment]
@GreysonMannix i will take some time to do a clean install of the whole package and will probably fix most of your issues including a working js build and docker image should be easy and linking the helpers proper is just one line i will reply again when im done.

**Comment by GreysonMannix** [comment]
I'd really appreciate it, thanks a lot!
Unfortunately I don't understand much about npm & co, otherwise I'd give a hand.

**Comment by tuefekci** [comment]
I have a built which works at the moment at least magnets and download works fine DDL and torrent is missing in this release I am still trying to rebuild it which should hopefully be done by Monday and I try to build a proper docker image and release it.

Sadly it looks like i never properly finished the logger, so I don't know really what happens with your downloads a try to implement it properly as well so that you post a log or dump of the error happening for you the only thing I can imagine is a chunk mismatch or if radarr or something like that already tried moving the files I never figured out a great way how to block them from starting to copy them, but I will try to put in a bit more love int blkhole there are a lot of areas which need love and if at least somebody else uses it my motivation will be a lot higher

**Comment by GreysonMannix** [comment]
Thanks a lot! I will be using it for sure.
It's a great tool and I'm surprised there's not a huge interest in it...
I will keep your motivation high :)

When you'll have this new version I'll test and try to take as much logs as I can.
I've found a lot of errors in radarr log about permissions to access and write.
Not sure why since they should be theoretically fine.
I have to do some checks but indeed running it via the command line seems to be problematic.

**Comment by tuefekci** [comment]
I could replicate the download not ready error need to figure out a fix it will work if you manually readd the download, and it will not redownload stuff it already downloaded in the past, so I just need to figure out how he ends up in a situation where he still knows the download did not work but does not restart it automatically.

**Comment by GreysonMannix** [comment]
Hello!
Any news?

**Comment by tuefekci** [comment]
@GreysonMannix Sorry had some problems and needed to switch machines, I'm working on a full rewrite (this was basically a project to get into reactive PHP, but it's harder to maintain so NodeJS it is) and hopefully can push something in the next days I'm also automating docker images and releases and extended logging so that bugs should be found easier in the future.

**Comment by GreysonMannix** [comment]
No problem, I've been busy as well lately...
Let me know if I can help!

**Comment by tuefekci** [comment]
Yeah im working on a complete rewrite should be able to get something stable together soon.
